---

- hosts: all
  remote_user: ec2-user
  become: true
  become_user: root
  tasks:
  - name: création des groupes
    group:
      name: "{{ item }}"
    with_items:
      - edelia
      - dev
      - rect
      - exploit
