---

- hosts: all
  remote_user: ec2-user 

  become: true
  become_user: root
  tasks:
  - name: création d'utilisateurs pour le hub_iot
    user:
      name: "{{ item.name }}"
      state : present
      group: "{{ item.group }}"
      groups: "{{item.groups }}"
    with_items:
      - { name: 'jmponsen', group: 'dev', groups: 'edelia' }
      - { name: 'mtecourt', group: 'dev', groups: 'edelia' }	
      - { name: 'sqasmi', group: 'dev', groups: 'edelia' }	
      - { name: 'lmolini', group: 'dev', groups: 'edelia' }	
      - { name: 'edubreuil', group: 'exploit', groups: 'wheel' }	
      - { name: 'indaw', group: 'exploit', groups: 'wheel' }	
      - { name: 'edelia', group: 'edelia', groups: '' }
      - { name: 'melsanharawi', group: 'dev', groups: 'edelia' }
      - { name: 'qbisson', group: 'dev', groups: 'edelia' }

 
